POST http://localhost:8080/user/admin?login=adam&password=test HTTP/1.1

// TODO: Fill the value
// 0bbaf544-482f-4389-96f9-1f95c88b5be5

###

POST http://localhost:8080/session?adminId=945b9eb7-c652-4206-bf65-94e9fe3fdcaa&name=test HTTP/1.1

// TODO: Fill the value
// 67d66f4b-2cac-4e07-b5d9-96d17f03aa34

###

POST http://localhost:8080/question/session/945b9eb7-c652-4206-bf65-94e9fe3fdcaa HTTP/1.1
Content-Type: application/json

{
    "question": "What device do you use?",
    "answers": [
        {
            "text": "Phone",
            "correct": false
        },
        {
            "text": "Mac",
            "correct": true
        }
    ]
}

###

GET http://localhost:8080/question/session/dcab84b4-ed40-4953-bc19-a4e34da5e300/index/1 HTTP/1.1